name: flutter_paystack_plus
description: Integrate Paystack for Mobile and Web with support for split payment and subscription features.
version: 2.3.0
homepage: https://github.com/excellonit/flutter_paystack_plus

environment:
  sdk: '>=2.18.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  js: ^0.7.1
  http: ^1.2.2
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true